apiVersion: v1
kind: Service
metadata:
  name: bus-server
  labels:
    app: bus-app
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8095
  selector:
    app: bus-app
    tier: frontend
